### ISSUE TITLE
Add a copy clipboard option on decryption page

### ISSUE THREAD

**Issue by gergnz** [sktan/snapsecret#4]
Once you decrypt the secret, in the text box, there should be a copy to clipboard button on the top right corner.

I tried a few vue3 clipboard libraries, but none really worked out of the box. Raising this for review/smarter vue people.

**Comment by sktan** [comment]
@gergnz you should be able to test the branch referenced in #5 to test this.

ATM I haven't figured out how to determine when the "Scrollbar" pops up, so the button placement might be a bit weird for any text that goes beyond initial the 5 rows.
